project:
  type: website
  #output-dir: docs
  preview:
    port: 4200

website:
  page-navigation: true
  title: "Fernando Neculqueo"
  #site-url: "https://beamilz.com/"
  #google-analytics: "G-2J79YYG9CZ"
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Fernando Neculqueo. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/fe-agronomia/
      - icon: instagram
        href: https://www.instagram.com/fe_neculqueo/
      - icon: linkedin
        href: https://www.linkedin.com/in/fernando-neculqueo-78096616a/
      - icon: envelope
        href: mailto:fernandoneculqueo@hotmail.com
      #- icon: newspaper
        #href: https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7129591797797797888
  navbar:
    right:
      - text: About
        menu:
          - text: English
            href: about.qmd
          - text: Português
            href: about-pt.qmd
          - text: Español
            href: about-es.qmd
      - text: Posts
        menu:
          - text: All posts
            href: posts/index.qmd
          - text: English
            href: posts/en.qmd
          - text: Português
            href: posts/pt.qmd
          - text: Español
            href: posts/es.qmd
      - text: Teaching
        href: teaching/index.qmd
      - text: Talks
        href: talks/index.qmd
      - text: Research
        menu:
          - text: Português
            href: research/index.qmd
#      - quarto.qmd
#      - videos.qmd
      # - text: Resume
      #   href: https://beatrizmilz.github.io/resume/index.pdf
      # - icon: newspaper
      #   href: https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7129591797797797888
      - icon: github
        href: https://github.com/fe-agronomia/blog_fneculqueo
      - icon: linkedin
        href: https://www.linkedin.com/in/fernando-neculqueo-78096616a/

lang: pt

format:
  html:
    smooth-scroll: true
    theme:
      - pulse
      - custom.scss
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

editor: visual

comments:
  giscus:
    repo: fe-agronomia/blog_fneculqueo

execute:
  freeze: true

